controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
getdata:
    path: /prueba
    controller: App\Controller\GetDataController::getData
